(()=>{
if(!/Oculto: Caçada/i.test(document.title||''))return;

const CASES=[
['A Casa que Respira','Uma família abandonou a casa no meio do jantar. Portas fecham sozinhas e sal some do armário.','O espírito estava preso à caixa d’água. O vínculo foi quebrado e a família pode voltar.','Sob o papel de parede há um símbolo queimado: três riscos fechando um círculo.'],
['Fome na Estrada 9','Caminhoneiros somem sempre no mesmo quilômetro. Só ficam pegadas que terminam no asfalto.','A criatura usava um túnel de drenagem como toca. O fogo encerrou a sequência de desaparecimentos.','Entre os restos há a placa de um caçador: E. WARD.'],
['O Homem do Cemitério','Um morto é visto todas as noites limpando o próprio túmulo. Quem fala com ele adoece.','O revenant foi devolvido ao repouso depois que o objeto que prendia sua raiva foi destruído.','Mira Vale identifica o símbolo dos casos anteriores: não é invocação; é um selo de contenção.'],
['Uivos em Pedra Clara','Animais aparecem sem sangue e moradores juram ouvir um uivo dentro das casas.','O predador foi abatido antes da próxima lua. As mortes param naquela noite.','No bolso de uma vítima há uma fotografia antiga de Helena Voss ao lado de Elias Ward.'],
['O Terceiro Sino','Um sino toca sozinho numa capela desativada. No terceiro toque, alguém desaparece.','O foco da assombração foi destruído antes do terceiro toque. A capela fica em silêncio.','Dentro do sino há uma fita: “Se você encontrou isto, o Arquivo 13 foi reaberto.” — Elias Ward.'],
['Quarto 214','Hóspedes acordam vendo uma mulher atrás do próprio reflexo. O quarto 214 está lacrado há doze anos.','O espelho original foi quebrado e os reflexos voltaram a obedecer aos vivos.','No verso do espelho: VOSS MENTIU.'],
['Pele na Cerca','Uma fazenda encontra peles presas ao arame, mas nenhum animal desapareceu.','A criatura foi cercada e abatida antes de alcançar a casa principal.','O sangue recolhido contém a mesma cinza ritual encontrada no Caso 1.'],
['A Noiva sem Reflexo','Uma noiva aparece em fotografias de casamentos onde nunca esteve. Sempre falta alguém no dia seguinte.','O álbum que mantinha a entidade ancorada foi queimado. Nenhuma nova fotografia aparece.','No registro do hotel, “Elias Ward” assinou o quarto 214 três semanas depois de sua morte oficial.'],
['A Fera do Açude','Pescadores ouvem uma criança pedindo ajuda no meio da água. Quem entra no açude não volta.','A isca sobrenatural foi identificada; a criatura foi atraída para terra firme e eliminada.','Um mapa encontrado na margem marca cinco cidades — exatamente os cinco capítulos do Arquivo 13.'],
['Preço da Encruzilhada','Moradores recebem exatamente o que pedem e perdem algo que nunca ofereceram.','O contrato foi quebrado e o cobrador enviado de volta antes da próxima cobrança.','O demônio chama Helena de “a mulher que já pagou uma vez”.'],
['Turno da Madrugada','Funcionários de um matadouro escutam máquinas ligando às 03:13, mesmo com a energia cortada.','O carniçal foi encontrado nos dutos e o prédio deixou de registrar movimento noturno.','Uma parede interna traz a frase: A PORTA TEM FOME.'],
['Voz no Berçário','Um hospital desativado recebe chamadas internas vindas do antigo berçário.','O possesso foi separado da entidade e sobreviveu. As chamadas cessaram.','Mira decodifica coordenadas escondidas na gravação: apontam para uma capela rural.'],
['O Matadouro Vazio','Caminhões chegam carregados e saem vazios, mas ninguém trabalha no local há meses.','O ninho foi eliminado. A polícia encontra os desaparecidos ainda vivos numa câmara fria.','Entre os pertences há páginas arrancadas do diário de Elias.'],
['A Capela que Anda','Motoristas juram que a mesma capela aparece em estradas diferentes durante a madrugada.','O ponto de ancoragem foi rompido e a capela voltou ao terreno onde deveria existir.','No altar: “Helena abriu. Eu fechei. Não foi suficiente.” — E.W.'],
['O Cavaleiro Oco','Uma armadura de procissão atravessa a cidade toda noite sem ninguém dentro.','A armadura foi desmontada e o selo no peitoral destruído.','Seu rádio recebe uma voz impossível: Elias Ward está vivo.'],
['Luz Morta','Uma igreja continua iluminada por dentro apesar de estar sem energia há vinte anos.','O arauto foi expulso e a luz artificial finalmente apaga.','Elias avisa: cada selo rompido está enfraquecendo algo maior.'],
['Cinzas que Andam','Pegadas de cinza aparecem em casas fechadas e terminam ao lado das camas.','A besta foi contida na pedreira onde nasceu. As marcas deixam de surgir.','Mira encontra o nome do projeto original: PROTOCOLO VÉU.'],
['A Igreja sem Som','Dentro da igreja ninguém consegue produzir som; do lado de fora, gritos são ouvidos.','O campo de silêncio foi quebrado e três pessoas presas no subsolo foram resgatadas.','O Protocolo Véu tem duas assinaturas: Helena Voss e Elias Ward.'],
['A Pedreira Negra','Operários extraem uma rocha que absorve luz. Depois disso, começam os sonhos compartilhados.','A rocha foi selada e devolvida ao poço mais profundo. Os sonhos param.','Helena admite que o Arquivo 13 não caçava monstros: estudava a Porta.'],
['Serafim Partido','Uma figura alada aparece sobre o mosteiro sempre que alguém tenta destruir os arquivos.','O serafim cai e os arquivos sobrevivem ao incêndio.','Helena confessa: ela abriu a primeira Porta. Elias ficou para fechá-la.'],
['Os Nomes Enterrados','Lápides novas surgem durante a noite com nomes de pessoas ainda vivas.','O Rei de Ossos perde o vínculo com o cemitério e os nomes desaparecem ao amanhecer.','Um dos nomes apagados é o seu. A data gravada é amanhã.'],
['A Testemunha','Uma mulher aparece em câmeras de segurança de todos os casos, sempre olhando diretamente para a lente.','A entidade é confrontada e perde a forma humana.','Ela diz que o Sem Nome não está atrás da Porta — ele é a própria Porta tentando lembrar um rosto.'],
['O Ossuário','Ossos de diferentes cidades começam a aparecer organizados numa única sala subterrânea.','O ritual de montagem é interrompido e o ossuário desaba sem vítimas.','Elias entrega a última página do diário: fechar a Porta exige alguém do lado de dentro.'],
['Último Arquivo','O Arquivo 13 original reaparece numa estação de pesquisa abandonada. Tudo está intacto.','Os guardiões do arquivo são derrotados e o caminho até a câmara principal é aberto.','Mira encontra uma terceira opção: quebrar o nome da Porta em vez de sacrificar um caçador.'],
['A Porta','As cinco rotas convergem. Helena, Mira e Elias chegam ao mesmo lugar pela primeira vez.','O Sem Nome é derrotado e a Porta perde sua forma. O Arquivo 13 finalmente deixa de ser um segredo.','A Porta fechou — mas uma página em branco surgiu no diário de Elias. Caçada+ começa aqui.']
];
const CHAPTER_META=[
{title:'O Selo de Cinza',objective:'Descobrir por que o mesmo símbolo aparece em casos sem relação.',summary:'Helena coordena suas caçadas à distância. Alguém parece preparar os monstros antes de você chegar.'},
{title:'O Nome Apagado',objective:'Descobrir se Elias Ward morreu mesmo — e o que Helena esconde.',summary:'Mira Vale entra na investigação. O passado de Helena e Elias começa a aparecer nos casos.'},
{title:'Vozes do Arquivo',objective:'Encontrar a origem do Protocolo Véu e localizar Elias.',summary:'Os casos deixaram de ser coincidência. Algo está usando cada criatura como parte de uma contenção maior.'},
{title:'A Verdade de Helena',objective:'Entender o que foi aberto no primeiro Arquivo 13.',summary:'Elias está vivo. Helena sabe mais do que admitiu. Cada vitória aproxima você da mesma Porta.'},
{title:'A Última Porta',objective:'Reunir Helena, Mira e Elias e impedir o Sem Nome.',summary:'O caso maior chega ao fim enquanto cada nova caçada ainda precisa ser encerrada por conta própria.'}
];
const BEATS={1:{who:'HELENA VOSS',icon:'📻',title:'Sua controladora',text:'“Você resolve o caso. Eu procuro o padrão. Não confunda as duas coisas.” Helena fala como quem já viu esse símbolo antes.'},3:{who:'MIRA VALE',icon:'🔬',title:'Consultora ocultista',text:'Mira entra na equipe sem pedir permissão a Helena. Ela trata monstros como evidência, não como lenda.'},5:{who:'ELIAS WARD',icon:'📼',title:'O caçador morto',text:'A fita de Elias prova que o Arquivo 13 existiu. Oficialmente, ele morreu há anos. A voz na gravação não parece antiga.'},10:{who:'HELENA VOSS',icon:'📻',title:'Primeira rachadura',text:'Depois da encruzilhada, Helena para de negar o passado. Ela ainda não conta tudo.'},15:{who:'ELIAS WARD',icon:'📡',title:'Sinal vivo',text:'Elias responde pelo rádio. Ele não pede resgate: pede que você pare de quebrar os selos.'},20:{who:'HELENA VOSS',icon:'🗝️',title:'A confissão',text:'Helena admite que abriu a primeira Porta durante o Protocolo Véu. Elias ficou do outro lado para fechá-la.'},24:{who:'MIRA VALE',icon:'📖',title:'Uma terceira saída',text:'Mira encontra uma alternativa ao sacrifício planejado por Elias. Pela primeira vez, o final não parece decidido.'},25:{who:'ARQUIVO 13',icon:'⬛',title:'Fim do primeiro arquivo',text:'A Porta fecha. Helena para de comandar, Mira começa a escrever e Elias finalmente volta a aparecer nos registros.'}};
const MONSTER_LORE={'Poltergeist':'Espíritos de pressão emocional. Eles não “assombram” uma casa: transformam memória em força física.','Wendigo':'Predador ligado a fome e isolamento. Quanto mais tempo caça sem ser visto, mais ousado se torna.','Revenant':'Um morto mantido ativo por raiva, promessa ou objeto. Destruir o corpo raramente basta.','Predador Lunar':'Caçador físico que reage à prata. Feridas comuns fecham rápido demais para serem confiáveis.','Noiva do Espelho':'Entidade de reflexo. Usa imagens, superfícies e lembranças para criar presença onde não existe corpo.','Demônio da Encruzilhada':'Negociador. O contrato é arma e fraqueza; toda oferta tem uma cláusula que você ainda não viu.','Carniçal':'Predador oportunista atraído por morte recente. Aprende rotas humanas com rapidez desagradável.','Possesso':'O corpo é vítima e campo de batalha. Símbolos e exorcismo são mais úteis que dano bruto.','Cavaleiro Oco':'Uma vontade presa a uma armadura ritual. Ferro consagrado interrompe o ciclo que a mantém de pé.','Arauto do Vazio':'Presença que apaga luz e referência. LUZ não é só dano: é uma forma de obrigá-lo a existir.','Besta de Cinzas':'Criatura que recompõe tecido a partir de resíduos rituais. Prata impede a reconstrução correta.','Serafim Partido':'Algo que já foi tratado como sagrado. A queda não removeu sua disciplina — apenas o propósito.','Rei de Ossos':'Entidade territorial que usa restos humanos como arquivo e exército.','A Testemunha':'Observa antes de agir. Sua força cresce quando sabe que está sendo percebida.','O Sem Nome':'Não há descrição confiável. Todo registro muda depois do contato.'};
const ARTIFACTS=[{id:'wardTape',name:'Fita de Ward',icon:'📼',desc:'+5 vida permanente. A primeira prova de que Elias antecipou o Arquivo 13.',boss:5,apply:()=>{p.life=(p.life||0)+5}},{id:'crossroadAsh',name:'Cinza da Encruzilhada',icon:'🩸',desc:'+1 dano permanente. Resíduo de um contrato que não terminou como deveria.',boss:10,apply:()=>{p.dmg=(p.dmg||0)+1}},{id:'hollowSeal',name:'Selo Oco',icon:'⛓️',desc:'+5 vida permanente. Parte do selo que mantinha o Cavaleiro de pé.',boss:15,apply:()=>{p.life=(p.life||0)+5}},{id:'veilLens',name:'Lente do Véu',icon:'🔬',desc:'+1 dano permanente. Mira a ajustou para enxergar onde a entidade realmente está.',boss:20,apply:()=>{p.dmg=(p.dmg||0)+1}},{id:'doorKey',name:'Chave sem Porta',icon:'🗝️',desc:'+1 energia máxima permanente. O metal continua morno mesmo longe da câmara.',boss:25,apply:()=>{p.storyEnergy=(p.storyEnergy||0)+1}}];
let pending=[],clock=null,deadline=0,pausedLeft=0,narrativePause=false;
const timerKey='oculto5-timer-v8';let timerEnabled=localStorage.getItem(timerKey)!=='off';const $=s=>document.querySelector(s),el=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){try{localStorage.oculto5=JSON.stringify(p)}catch(e){}}
function ensureStory(){p.story=p.story||{};p.story.version=8;p.story.seenCases=p.story.seenCases||[];p.story.seenMonsters=p.story.seenMonsters||[];p.story.seenCards=p.story.seenCards||[];p.story.seenRelics=p.story.seenRelics||[];p.story.seenBeats=p.story.seenBeats||[];p.story.artifacts=p.story.artifacts||{};p.story.evidence=Math.max(p.story.evidence||0,Math.min(p.campaignPos||0,25));if(!p.story.migratedV8){const upto=Math.min(p.campaignPos||0,25);p.story.seenCases=Array.from({length:upto},(_,i)=>i);for(let pos=0;pos<upto;pos++){const ch=Math.floor(pos/5),ci=pos%5,idx=ci===4?Math.min(E.length-1,ch*3+2):Math.min(E.length-1,ch*3+(ci%3));if(E[idx])p.story.seenMonsters.push(E[idx][0])}p.story.seenMonsters=[...new Set(p.story.seenMonsters)];p.story.seenCards=[...new Set(C.filter(c=>c.l<=p.lv).map(c=>c.id))];p.story.seenRelics=Object.keys(p.relics||{}).filter(k=>(p.relics[k]||0)>0);Object.keys(BEATS).map(Number).filter(n=>n<=upto).forEach(n=>p.story.seenBeats.push(n));let converted=0;Object.keys(p.relics||{}).forEach(k=>{const n=Number(p.relics[k])||0;if(n>1){converted+=(n-1)*15;p.relics[k]=1}});if(converted){p.ess=(p.ess||0)+converted;p.story.convertedRelics=converted}p.story.migratedV8=true;persist()}}
ensureStory();
const oldEnergy=energy;energy=function(){return oldEnergy()+(p.storyEnergy||0)};
function secondsForFight(){return({story:18,hunter:15,veteran:12,nightmare:10}[p.diff]||15)}function activeFight(){return !!(b&&el('battle')?.classList.contains('on')&&b.hp>0&&b.php>0&&!el('modal')?.classList.contains('on'))}
function ensureTimerUI(){const head=$('#battle .battleHead');if(!head)return;let box=el('v8-timer');if(!box){box=document.createElement('div');box.id='v8-timer';box.className='v8-timer';box.innerHTML='<button id="v8-timer-toggle" type="button"></button><div class="v8-clock"><span id="v8-clock-copy"></span><div><i id="v8-clock-fill"></i></div></div>';head.after(box);el('v8-timer-toggle').onclick=()=>toggleTimer()}updateTimerUI()}
function updateTimerUI(ms){ensureSettings();const box=el('v8-timer');if(box){box.classList.toggle('off',!timerEnabled);el('v8-timer-toggle').textContent=timerEnabled?'⏱ PRESSÃO ON':'⏸ SEM TEMPO';const total=secondsForFight()*1000,left=Math.max(0,ms??(deadline?deadline-Date.now():total));el('v8-clock-copy').textContent=timerEnabled?`${Math.ceil(left/1000)}s até o ataque`:'Inimigo só ataca ao encerrar turno';el('v8-clock-fill').style.width=(timerEnabled?Math.max(0,Math.min(100,left/total*100)):100)+'%'}const btn=el('v8-home-timer');if(btn){btn.textContent=timerEnabled?'⏱ TEMPO: LIGADO':'⏸ TEMPO: DESLIGADO';btn.classList.toggle('on',timerEnabled)}}
function clearClock(){if(clock){clearInterval(clock);clock=null}deadline=0}function pauseClock(){if(!timerEnabled||!deadline)return;pausedLeft=Math.max(300,deadline-Date.now());clearClock()}function resumeClock(){if(!timerEnabled||!activeFight()||narrativePause)return;startClock(pausedLeft||secondsForFight()*1000);pausedLeft=0}
function startClock(ms){clearClock();if(!timerEnabled||!activeFight()||narrativePause){updateTimerUI();return}deadline=Date.now()+(ms||secondsForFight()*1000);clock=setInterval(()=>{if(!activeFight()){clearClock();return}if(document.hidden||narrativePause){pauseClock();return}const left=deadline-Date.now();updateTimerUI(left);if(left<=0){clearClock();endTurn()}},120);updateTimerUI(ms)}
function toggleTimer(){timerEnabled=!timerEnabled;localStorage.setItem(timerKey,timerEnabled?'on':'off');if(timerEnabled){pausedLeft=0;startClock()}else{clearClock();pausedLeft=0}updateTimerUI();if(window.V7Toast)V7Toast(timerEnabled?'Pressão de tempo ligada. O inimigo ataca quando o relógio zerar.':'Pressão de tempo desligada. Você controla o fim do turno.',timerEnabled?'gold':'')}
window.V8ToggleTimer=toggleTimer;document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseClock();else resumeClock()});
function storyChapter(pos=p.campaignPos||0){return Math.min(4,Math.floor(Math.min(pos,24)/5))}
function charStatus(){const n=p.campaignPos||0;return[['📻','Helena Voss',n<10?'Controladora • reservada':n<20?'Controladora • sob suspeita':n<25?'No campo • verdade revelada':'Arquivo encerrado'],['🔬','Mira Vale',n<2?'Ainda não entrou na equipe':n<17?'Consultora • decifrando o selo':n<24?'Consultora • Protocolo Véu':'Autora do novo arquivo'],['📼','Elias Ward',n<5?'Morto oficialmente':n<14?'Sinais impossíveis':n<20?'Vivo • preso ao Véu':n<25?'Voltando para a Porta':'De volta aos registros']]}
function ensureSettings(){const panel=$('#home .panel');if(!panel)return;let s=el('v8-settings');if(!s){s=document.createElement('div');s.id='v8-settings';s.className='v8-settings';s.innerHTML='<div><b>RITMO DA CAÇADA</b><small>Com tempo ligado, o inimigo não espera você encerrar o turno.</small></div><button id="v8-home-timer" type="button"></button>';const diff=panel.querySelector('.diff');diff?.parentNode.insertBefore(s,diff);el('v8-home-timer').onclick=toggleTimer}const btn=el('v8-home-timer');if(btn){btn.textContent=timerEnabled?'⏱ TEMPO: LIGADO':'⏸ TEMPO: DESLIGADO';btn.classList.toggle('on',timerEnabled)}}
function renderStoryHome(){const panel=$('#home .panel');if(!panel)return;ensureSettings();let card=el('v8-story-home');if(!card){card=document.createElement('div');card.id='v8-story-home';card.className='v8-story-home';const camp=panel.querySelector('.campaign');camp?.after(card)}const ch=storyChapter(),m=CHAPTER_META[ch],pos=Math.min(p.campaignPos||0,25),last=pos?CASES[Math.min(24,pos-1)][3]:'Nenhuma pista coletada ainda.';card.innerHTML=`<div class="v8-story-head"><div><small>FIO VERMELHO // HISTÓRIA DE FUNDO</small><b>${esc(m.title)}</b></div><strong>${pos}/25</strong></div><p>${esc(m.summary)}</p><div class="v8-objective"><span>OBJETIVO ATUAL</span><b>${esc(m.objective)}</b></div><div class="v8-last"><span>ÚLTIMA PISTA</span>${esc(last)}</div><div class="v8-people">${charStatus().map(x=>`<div><i>${x[0]}</i><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}</div><div class="v8-home-actions"><button onclick="V8Archive()">🗂 ARQUIVO DA CAÇADA</button><button onclick="V8Story()">📖 HISTÓRIA</button></div>`}
window.V8Story=()=>openStory();window.V8Archive=()=>openArchive();
function modal(title,kicker,body,buttons=[['CONTINUAR',closeV8]]){closeV8(false);narrativePause=true;pauseClock();const o=document.createElement('div');o.id='v8-overlay';o.className='v8-overlay';o.innerHTML=`<div class="v8-sheet"><div class="v8-k">${esc(kicker||'ARQUIVO 13')}</div><h2>${esc(title)}</h2><div class="v8-body">${body}</div><div class="v8-actions" id="v8-actions"></div></div>`;document.body.appendChild(o);const a=el('v8-actions');buttons.forEach(([label,fn,cls])=>{const bt=document.createElement('button');bt.textContent=label;bt.className=cls||'';bt.onclick=fn;a.appendChild(bt)})}
function closeV8(resume=true){el('v8-overlay')?.remove();narrativePause=false;if(resume)resumeClock()}function queue(x){pending.push(x)}function nextPending(){if(!pending.length)return;const x=pending.shift();modal(x.title,x.kicker,x.body,[['CONTINUAR',()=>{closeV8(false);nextPending()}]])}
function openStory(){const ch=storyChapter(),m=CHAPTER_META[ch];modal(m.title,'FIO VERMELHO',`<p>${esc(m.summary)}</p><div class="v8-objective"><span>OBJETIVO</span><b>${esc(m.objective)}</b></div><div class="v8-people full">${charStatus().map(x=>`<div><i>${x[0]}</i><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}</div><p class="v8-muted">A história de fundo avança com as pistas dos casos. Cada luta fecha seu próprio problema, mas deixa algo para o Arquivo 13.</p>`)}
function openArchive(){const seen=Math.min(p.campaignPos||0,25),rows=Array.from({length:seen},(_,i)=>{const c=CASES[i];return `<button class="v8-case-row" onclick="V8Case(${i})"><span>${String(i+1).padStart(2,'0')}</span><div><b>${esc(c[0])}</b><small>${esc(c[2])}</small></div></button>`}).join('')||'<p>Nenhum caso encerrado ainda.</p>';const rel=Object.keys(p.relics||{}).filter(id=>(p.relics[id]||0)>0).map(id=>RELICS.find(r=>r.id===id)).filter(Boolean);const arts=ARTIFACTS.filter(a=>p.story.artifacts[a.id]);modal('Arquivo da Caçada','CASOS • RELÍQUIAS • EVIDÊNCIAS',`<div class="v8-tabs-copy"><b>${seen} casos encerrados</b> • ${p.story.seenMonsters.length} entidades catalogadas</div><div class="v8-case-list">${rows}</div><h3>Artefatos da história</h3><div class="v8-chiplist">${arts.map(a=>`<span>${a.icon} ${esc(a.name)}</span>`).join('')||'<small>Nenhum ainda.</small>'}</div><h3>Relíquias únicas</h3><div class="v8-chiplist">${rel.map(r=>`<span>🧿 ${esc(r.name)}</span>`).join('')||'<small>Nenhuma ainda.</small>'}</div>`)}
window.V8Case=i=>{const c=CASES[i];modal(c[0],`CASO ${String(i+1).padStart(2,'0')} // ENCERRADO`,`<p><b>Chamado:</b> ${esc(c[1])}</p><p><b>Desfecho:</b> ${esc(c[2])}</p><div class="v8-clue"><span>PISTA DO FIO VERMELHO</span>${esc(c[3])}</div>`,[['VOLTAR AO ARQUIVO',()=>{closeV8(false);openArchive()}]])};
function showCaseIntro(){if(!b)return;const pos=Math.min(24,b.casePos%25),c=CASES[pos],firstMonster=!p.story.seenMonsters.includes(b.name);let body=`<p class="v8-hook">${esc(c[1])}</p><div class="v8-brief"><div><span>LOCAL</span><b>${esc(b.place)}</b></div><div><span>ENTIDADE</span><b>${esc(b.name)}</b></div><div><span>FRAQUEZA</span><b>${esc(b.weak)}</b></div></div>`;if(firstMonster)body+=`<div class="v8-new"><strong>NOVA ENTIDADE CATALOGADA</strong><div class="v8-monster"><i>${b.icon}</i><div><b>${esc(b.name)}</b><p>${esc(MONSTER_LORE[b.name]||b.desc)}</p></div></div></div>`;body+=`<div class="v8-background"><span>FIO DE FUNDO</span>${esc(CHAPTER_META[storyChapter(pos)].objective)}</div>`;modal(c[0],`CASO ${String(pos+1).padStart(2,'0')} // ${b.boss?'CHEFE DE CAPÍTULO':'CHAMADO'}`,body,[['INICIAR CAÇADA',()=>{if(firstMonster){p.story.seenMonsters.push(b.name);persist()}closeV8();startClock()}]])}
function presentCard(c){queue({title:c.n,kicker:'NOVO EQUIPAMENTO DESBLOQUEADO',body:`<div class="v8-item-big"><i>${c.i}</i><div><b>${esc(c.n)}</b><p>Tipo: <strong>${esc(c.t)}</strong> • custo ${c.c} energia.</p><p>${c.d?`${c.d} dano base. `:''}${c.s?`+${c.s} proteção. `:''}${c.h?`Cura ${c.h}. `:''}${c.st?'Impede um ataque.':''}</p></div></div><p>Esta carta agora entra no seu conjunto de possíveis mãos em todas as próximas caçadas.</p>`})}
function presentRelic(r){queue({title:r.name,kicker:'RELÍQUIA ÚNICA ADQUIRIDA',body:`<div class="v8-item-big"><i>🧿</i><div><b>${esc(r.name)}</b><p>${esc(r.desc)}</p></div></div><p>Relíquias agora são únicas: depois de adquirida, esta não volta a aparecer como prêmio.</p>`})}
function presentArtifact(a){queue({title:a.name,kicker:'ARTEFATO DO FIO VERMELHO',body:`<div class="v8-item-big"><i>${a.icon}</i><div><b>${esc(a.name)}</b><p>${esc(a.desc)}</p></div></div><p>Este objeto veio da história principal e permanece com você pelo resto da campanha.</p>`})}
function beatIfNew(completed){const x=BEATS[completed];if(!x||p.story.seenBeats.includes(completed))return;p.story.seenBeats.push(completed);queue({title:x.title,kicker:`${x.icon} ${x.who}`,body:`<p class="v8-hook">${esc(x.text)}</p><p class="v8-muted">Essa mudança pertence à história de fundo. O próximo caso continua sendo um problema fechado por si só.</p>`})}
showRewards=function(){const wrap=el('rewardWrap'),btn=el('continueBtn');if(!b?.boss){wrap.style.display='none';btn.disabled=false;return}const available=RELICS.filter(r=>(p.relics?.[r.id]||0)<=0).sort(()=>Math.random()-.5).slice(0,3);if(!available.length){p.ess=(p.ess||0)+25;persist();wrap.style.display='block';wrap.innerHTML='<p><b>Relíquias do Arquivo completas.</b></p><div class="sum">+25 essência concentrada no lugar de uma relíquia repetida.</div>';btn.disabled=false;return}wrap.style.display='block';btn.disabled=true;wrap.innerHTML='<p><b>Relíquia de chefe — escolha 1 item único:</b><br><small>Itens já adquiridos não voltam a aparecer.</small></p><div class="rewardGrid" id="rewards"></div>';el('rewards').innerHTML=available.map(r=>`<button class="reward" onclick="pickReward('${r.id}',this)"><strong>${esc(r.name)}</strong><small>${esc(r.desc)}</small></button>`).join('')};
const basePick=pickReward;pickReward=function(id,node){const r=RELICS.find(x=>x.id===id),had=(p.relics?.[id]||0)>0;if(had)return;const out=basePick(id,node);if(r){p.relics[id]=1;if(!p.story.seenRelics.includes(id))p.story.seenRelics.push(id);persist();presentRelic(r)}return out};
const baseStart=start;start=function(){clearClock();pausedLeft=0;const out=baseStart();setTimeout(()=>{ensureTimerUI();showCaseIntro()},30);return out};const baseResume=resumeBattle;resumeBattle=function(){clearClock();const out=baseResume();setTimeout(()=>{ensureTimerUI();startClock()},30);return out};const baseEnd=endTurn;endTurn=function(){clearClock();const out=baseEnd();setTimeout(()=>{if(activeFight())startClock()},40);return out};const baseRender=render;render=function(){const out=baseRender();ensureTimerUI();return out};const baseHome=home;home=function(){const out=baseHome();setTimeout(renderStoryHome,0);return out};
const baseWin=win;win=function(){clearClock();const before={lv:p.lv,life:life(),dmg:dmg(),energy:energy(),pos:p.campaignPos};const wasBoss=!!b?.boss;const out=baseWin();if(p.campaignPos===before.pos)return out;ensureStory();const pos=Math.min(24,before.pos%25),c=CASES[pos];p.story.evidence=Math.max(p.story.evidence||0,Math.min(p.campaignPos,25));if(!p.story.seenCases.includes(pos))p.story.seenCases.push(pos);const gained=C.filter(card=>card.l>before.lv&&card.l<=p.lv&&!p.story.seenCards.includes(card.id));gained.forEach(card=>{p.story.seenCards.push(card.id);presentCard(card)});let artifact=null;if(wasBoss){artifact=ARTIFACTS.find(a=>a.boss===p.campaignPos&&!p.story.artifacts[a.id]);if(artifact){artifact.apply();p.story.artifacts[artifact.id]=true;presentArtifact(artifact)}}beatIfNew(p.campaignPos);persist();let extra=`<div class="v8-win-story"><span>CASO ENCERRADO // ${esc(c[0])}</span><p>${esc(c[2])}</p><div class="v8-clue"><span>PISTA DO FIO VERMELHO</span>${esc(c[3])}</div></div>`;if(p.lv>before.lv){extra+=`<div class="v8-levelup"><span>EVOLUÇÃO CUMULATIVA</span><b>Nível ${before.lv} → ${p.lv}</b><p>❤️ Vida ${before.life} → ${life()} • ⚔️ Dano +${before.dmg} → +${dmg()} • ⚡ Energia ${before.energy} → ${energy()}</p>${gained.length?`<p><strong>Novo equipamento:</strong> ${gained.map(x=>esc(x.n)).join(', ')}</p>`:'<p>Os ganhos deste nível foram aplicados automaticamente e permanecem nos próximos casos.</p>'}</div>`}if(artifact)extra+=`<div class="v8-artifact-inline">${artifact.icon} <b>${esc(artifact.name)}</b> adquirido automaticamente.</div>`;el('ms').insertAdjacentHTML('beforeend',extra);renderStoryHome();return out};
const baseLose=lose;lose=function(){clearClock();const pos=Math.min(24,(b?.casePos||p.campaignPos)%25),c=CASES[pos];const out=baseLose();el('ms')?.insertAdjacentHTML('beforeend',`<div class="v8-win-story fail"><span>CASO AINDA ABERTO // ${esc(c[0])}</span><p>Você sobreviveu à tentativa, mas o ciclo deste caso precisa ser refeito. A história de fundo não avança com uma derrota.</p></div>`);return out};const baseClose=closeModal;closeModal=function(){clearClock();const out=baseClose();setTimeout(()=>{renderStoryHome();nextPending()},60);return out};
renderStoryHome();setTimeout(()=>{if(p.story.convertedRelics&&!p.story.convertNotice){p.story.convertNotice=true;persist();modal('Relíquias reorganizadas','MIGRAÇÃO DO ARQUIVO',`<p>Relíquias agora são <b>únicas</b>. Duplicatas antigas foram convertidas em <b>${p.story.convertedRelics} essência</b>, preservando o valor do seu progresso.</p>`,[['ENTENDI',()=>{closeV8();if(!p.story.introV8){p.story.introV8=true;persist();showV8Intro()}}]])}else if(!p.story.introV8){p.story.introV8=true;persist();showV8Intro()}},160);
function showV8Intro(){modal('Dois fios, uma caçada','ARQUIVO 13 // NOVA ESTRUTURA',`<p><b>Caso da vez:</b> cada luta agora começa com um chamado próprio e termina com um desfecho daquele problema.</p><p><b>Fio Vermelho:</b> as pistas, Helena, Mira e Elias continuam evoluindo por trás dos casos até a Porta.</p><p><b>Pressão de tempo:</b> vem ligada por padrão. Quando o relógio zera, o inimigo ataca mesmo que você não encerre o turno. Pode ser desligada a qualquer momento.</p><p><b>Recompensas:</b> níveis aplicam ganhos cumulativos; cartas novas são apresentadas; relíquias são únicas e reservadas para chefes.</p>`)}
})();
